import JSZip from 'jszip'
import { ASPECT_RATIOS, PLATFORMS } from '../data/config'
import { applyListingPreset } from '../data/listingPresets'
import { applyTemplateSwitch } from '../data/presets'
import type { AspectRatio, CreativeData, ListingData, Platform, TemplateId } from '../types/creative'
import { generateCaptions } from './captionGenerator'
import { buildCampaignSlug, buildExportFilename } from './exportNaming'
import { generatePosterVariants } from './posterVariants'
import { renderCreativeToDataUrl } from './renderCreative'

export type ExportProgressFn = (message: string, percent: number) => void

const LISTING_CAMPAIGN: {
  status: ListingData['listingStatus']
  folder: string
  label: string
  templateId: TemplateId
}[] = [
  { status: 'just-listed', folder: 'just-listed', label: 'Just Listed', templateId: 'just-listed' },
  { status: 'open-house', folder: 'open-house', label: 'Open House', templateId: 'open-house' },
  { status: 'price-drop', folder: 'price-drop', label: 'Price Drop', templateId: 'price-drop' },
]

const CAPTION_PLATFORMS: Platform[] = ['instagram', 'linkedin', 'whatsapp']

function downloadZip(blob: Blob, filename: string) {
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = filename
  link.click()
  URL.revokeObjectURL(link.href)
}

function formatPosterCaptions(data: CreativeData, label: string): string {
  const caps = generateCaptions(data, 'professional')
  const lines = [
    `# ${label}`,
    `Property: ${data.propertyTitle || data.title}`,
    `Price: ${data.propertyPrice || '—'}`,
    '',
  ]
  for (const platform of CAPTION_PLATFORMS) {
    const c = caps[platform]
    lines.push(`--- ${platform.toUpperCase()} ---`, c.caption, c.hashtags, '')
  }
  return lines.join('\n')
}

function formatMasterCaptionPack(data: CreativeData): string {
  const caps = generateCaptions(data, 'professional')
  const lines = [
    'CREATIVE STUDIO PRO — CAPTION PACK',
    `Generated: ${new Date().toLocaleString()}`,
    `Poster: ${data.title}`,
    '',
  ]
  for (const p of PLATFORMS) {
    const c = caps[p.id]
    lines.push(
      `=== ${p.id.toUpperCase()} (score ${c.engagementScore}%) ===`,
      c.caption,
      c.hashtags || '(no hashtags)',
      '',
    )
  }
  return lines.join('\n')
}

async function addAllSizesToZip(
  zip: JSZip,
  folder: string,
  data: CreativeData,
  format: 'png' | 'jpeg',
  suffix?: string,
  onProgress?: ExportProgressFn,
  progressBase = 0,
  progressSpan = 1,
) {
  for (let i = 0; i < ASPECT_RATIOS.length; i++) {
    const ratio = ASPECT_RATIOS[i]
    onProgress?.(`Rendering ${folder} ${ratio.id}…`, progressBase + ((i + 1) / ASPECT_RATIOS.length) * progressSpan)
    const url = await renderCreativeToDataUrl(data, ratio.id as AspectRatio, format)
    const filename = buildExportFilename(data, ratio.id as AspectRatio, suffix, format)
    zip.file(`${folder}/${filename}`, url.split(',')[1], { base64: true })
  }
}

export async function exportListingCampaignPack(
  baseData: CreativeData,
  format: 'png' | 'jpeg' = 'png',
  onProgress?: ExportProgressFn,
) {
  if (!baseData.propertyTitle.trim() && !baseData.propertyPrice.trim()) {
    throw new Error('Add property title or price before exporting campaign pack')
  }

  const zip = new JSZip()
  const slug = buildCampaignSlug(baseData)
  const step = 80 / LISTING_CAMPAIGN.length

  zip.file(
    'README.txt',
    [
      'LISTING CAMPAIGN PACK',
      `Property: ${baseData.propertyTitle || baseData.title}`,
      `Price: ${baseData.propertyPrice || '—'}`,
      '',
      'Folders:',
      '  just-listed/   — 4 aspect ratios + captions.txt',
      '  open-house/    — 4 aspect ratios + captions.txt',
      '  price-drop/    — 4 aspect ratios + captions.txt',
      '  captions/      — master caption pack',
      '',
      'Generated by Creative Studio Pro',
    ].join('\n'),
  )

  for (let i = 0; i < LISTING_CAMPAIGN.length; i++) {
    const item = LISTING_CAMPAIGN[i]
    onProgress?.(`Building ${item.label}…`, 5 + i * step)
    const switched = applyTemplateSwitch(item.templateId, baseData)
    const patch = applyListingPreset(item.status, { ...baseData, ...switched })
    const posterData: CreativeData = { ...switched, ...patch }

    await addAllSizesToZip(zip, item.folder, posterData, format, undefined, onProgress, 5 + i * step, step * 0.85)
    zip.file(`${item.folder}/captions.txt`, formatPosterCaptions(posterData, item.label))
  }

  onProgress?.('Writing caption pack…', 88)
  zip.file('captions/master-caption-pack.txt', formatMasterCaptionPack(baseData))
  for (const platform of CAPTION_PLATFORMS) {
    const caps = generateCaptions(baseData, 'professional')
    zip.file(`captions/${platform}.txt`, `${caps[platform].caption}\n\n${caps[platform].hashtags}`)
  }

  onProgress?.('Creating ZIP…', 95)
  const blob = await zip.generateAsync({ type: 'blob' })
  downloadZip(blob, `${slug}-listing-campaign.zip`)
  onProgress?.('Done!', 100)
}

export async function exportAbVariantPack(
  baseData: CreativeData,
  format: 'png' | 'jpeg' = 'png',
  onProgress?: ExportProgressFn,
) {
  const variants = generatePosterVariants(baseData)
  const zip = new JSZip()
  const slug = buildCampaignSlug(baseData)
  const step = 90 / variants.length

  zip.file(
    'README.txt',
    [
      'A/B/C POSTER VARIANT PACK',
      `Base: ${baseData.title}`,
      '',
      'variant-a/ — baseline design',
      'variant-b/ — bold CTA highlight',
      'variant-c/ — palette shift',
      '',
      'Each folder contains all 4 aspect ratios.',
    ].join('\n'),
  )

  for (let i = 0; i < variants.length; i++) {
    const v = variants[i]
    onProgress?.(`Rendering variant ${v.id.toUpperCase()}…`, 5 + i * step)
    const variantData: CreativeData = { ...baseData, ...v.patch }
    await addAllSizesToZip(
      zip,
      `variant-${v.id}`,
      variantData,
      format,
      v.id,
      onProgress,
      5 + i * step,
      step * 0.9,
    )
    zip.file(`variant-${v.id}/variant-info.txt`, `${v.label}\n${v.desc}\nScore: ${v.score}%`)
  }

  onProgress?.('Creating ZIP…', 96)
  const blob = await zip.generateAsync({ type: 'blob' })
  downloadZip(blob, `${slug}-ab-variants.zip`)
  onProgress?.('Done!', 100)
}

export async function exportCaptionPack(baseData: CreativeData) {
  const slug = buildCampaignSlug(baseData)
  const zip = new JSZip()
  zip.file('master-caption-pack.txt', formatMasterCaptionPack(baseData))
  const caps = generateCaptions(baseData, 'professional')
  for (const p of PLATFORMS) {
    zip.file(`${p.id}.txt`, `${caps[p.id].caption}\n\n${caps[p.id].hashtags}`)
  }
  const blob = await zip.generateAsync({ type: 'blob' })
  downloadZip(blob, `${slug}-captions.zip`)
}

const MAX_BULK_LISTINGS = 20

export async function exportBulkListingCampaign(
  listingPatches: Partial<CreativeData>[],
  baseData: CreativeData,
  format: 'png' | 'jpeg' = 'png',
  onProgress?: ExportProgressFn,
) {
  const listings = listingPatches.slice(0, MAX_BULK_LISTINGS)
  if (listings.length === 0) throw new Error('No listings to export')

  const zip = new JSZip()
  const slug = buildCampaignSlug(baseData)
  const perListing = 90 / listings.length

  zip.file(
    'README.txt',
    [
      'BULK LISTING CAMPAIGN EXPORT',
      `Listings: ${listings.length}`,
      '',
      'Each listing-N/ folder contains:',
      '  just-listed/, open-house/, price-drop/ with 4 sizes each + captions',
      '',
      'Generated by Creative Studio Pro',
    ].join('\n'),
  )

  for (let i = 0; i < listings.length; i++) {
    const patch = listings[i]
    const listingData: CreativeData = { ...baseData, ...patch }
    const folder = `listing-${String(i + 1).padStart(2, '0')}-${slugPart(listingData.propertyTitle || listingData.title || 'property', 20)}`
    const basePct = 5 + i * perListing

    onProgress?.(`Listing ${i + 1}/${listings.length}…`, basePct)

    for (let j = 0; j < LISTING_CAMPAIGN.length; j++) {
      const item = LISTING_CAMPAIGN[j]
      const subStep = perListing / LISTING_CAMPAIGN.length
      const switched = applyTemplateSwitch(item.templateId, listingData)
      const preset = applyListingPreset(item.status, { ...listingData, ...switched })
      const posterData: CreativeData = { ...switched, ...preset }
      const subFolder = `${folder}/${item.folder}`

      await addAllSizesToZip(
        zip,
        subFolder,
        posterData,
        format,
        undefined,
        onProgress,
        basePct + j * subStep,
        subStep * 0.85,
      )
      zip.file(`${subFolder}/captions.txt`, formatPosterCaptions(posterData, item.label))
    }
  }

  onProgress?.('Creating bulk ZIP…', 96)
  const blob = await zip.generateAsync({ type: 'blob' })
  downloadZip(blob, `${slug}-bulk-${listings.length}-listings.zip`)
  onProgress?.('Done!', 100)
}

function slugPart(value: string, max = 24): string {
  return value.slice(0, max).replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase() || 'listing'
}
